-- =========================================================
-- INTELLIGENT SQL QUERY PROFILER & INDEX OPTIMIZATION ENGINE
-- Database Schema
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- PART 1: APPLICATION / BUSINESS TABLES
-- =========================================================


-- ---------------------------------------------------------
-- 1. CUSTOMERS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,

    email VARCHAR(150) NOT NULL,

    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),

    registration_date DATE NOT NULL,

    customer_status VARCHAR(20) NOT NULL
);


-- ---------------------------------------------------------
-- 2. PRODUCTS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_name VARCHAR(200) NOT NULL,

    category VARCHAR(100),

    price NUMERIC(12,2) NOT NULL,

    stock_quantity INTEGER NOT NULL,

    supplier VARCHAR(150),

    product_status VARCHAR(20) NOT NULL
);


-- ---------------------------------------------------------
-- 3. ORDERS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT NOT NULL,

    order_date TIMESTAMP NOT NULL,

    order_status VARCHAR(30) NOT NULL,

    total_amount NUMERIC(14,2) NOT NULL,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);


-- ---------------------------------------------------------
-- 4. ORDER ITEMS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,

    quantity INTEGER NOT NULL,

    unit_price NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);


-- ---------------------------------------------------------
-- 5. PAYMENTS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    payment_date TIMESTAMP NOT NULL,

    payment_method VARCHAR(30),

    payment_status VARCHAR(30),

    amount NUMERIC(14,2) NOT NULL,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);


-- ---------------------------------------------------------
-- 6. SHIPMENTS
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS shipments (
    shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    shipment_date TIMESTAMP,

    delivery_date TIMESTAMP,

    shipping_method VARCHAR(50),

    shipment_status VARCHAR(30),

    destination_city VARCHAR(100),

    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);



-- =========================================================
-- PART 2: QUERY PROFILER TABLES
-- =========================================================


-- ---------------------------------------------------------
-- 7. QUERY PROFILES
--
-- Stores queries observed and analyzed by our system.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS query_profiles (
    query_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    query_hash VARCHAR(64) NOT NULL,

    query_text TEXT NOT NULL,

    query_type VARCHAR(30),

    execution_count BIGINT DEFAULT 0,

    total_execution_time_ms DOUBLE PRECISION DEFAULT 0,

    average_execution_time_ms DOUBLE PRECISION DEFAULT 0,

    rows_processed BIGINT DEFAULT 0,

    table_name VARCHAR(100),

    captured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ---------------------------------------------------------
-- 8. INDEX RECOMMENDATIONS
--
-- Stores indexes proposed by the recommendation engine.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS index_recommendations (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    query_profile_id BIGINT,

    table_name VARCHAR(100) NOT NULL,

    column_name VARCHAR(100) NOT NULL,

    index_type VARCHAR(30) DEFAULT 'BTREE',

    recommendation_score DOUBLE PRECISION,

    priority VARCHAR(20),

    reasoning TEXT,

    index_sql TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_recommendation_query
        FOREIGN KEY (query_profile_id)
        REFERENCES query_profiles(query_profile_id)
);


-- ---------------------------------------------------------
-- 9. BENCHMARK RESULTS
--
-- Stores BEFORE vs AFTER index performance.
-- ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS benchmark_results (
    benchmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    recommendation_id BIGINT,

    query_text TEXT NOT NULL,

    execution_time_before_ms DOUBLE PRECISION,

    execution_time_after_ms DOUBLE PRECISION,

    improvement_percentage DOUBLE PRECISION,

    rows_before BIGINT,

    rows_after BIGINT,

    before_plan TEXT,

    after_plan TEXT,

    benchmarked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_benchmark_recommendation
        FOREIGN KEY (recommendation_id)
        REFERENCES index_recommendations(recommendation_id)
);



-- =========================================================
-- END OF SCHEMA
-- =========================================================
