"""
Recommendation / Candidate Scoring Engine
------------------------------------------
Scores index candidates using SQL metadata and
execution-plan evidence.

This module DOES NOT create indexes.

It only:
1. Scores candidates.
2. Explains the score.
3. Produces a ranked list.
"""


# =========================================================
# SCORE CANDIDATES
# =========================================================

def score_index_candidates(
    candidates,
    features,
    query_metadata
):
    """
    Score index candidates using available evidence.

    Parameters
    ----------
    candidates : list of dict
        Candidates generated by index_candidate_generator.

    features : dict
        Features extracted from the execution plan.

    query_metadata : dict
        Metadata extracted from query_parser.

    Returns
    -------
    list of dict
        Scored and ranked candidates.
    """

    scored_candidates = []

    for candidate in candidates:

        score = 0
        reasons = []

        table = candidate["table_name"]
        column = candidate["column_name"]
        reason = candidate["reason"]

        # -------------------------------------------------
        # 1. Filter evidence
        # -------------------------------------------------

        filter_match = False

        for filter_info in features.get(
            "filters",
            []
        ):

            filter_table = filter_info.get(
                "table"
            )

            condition = filter_info.get(
                "condition"
            )

            if (
                filter_table == table
                and condition
                and column in condition
            ):

                filter_match = True

                score += 30

                reasons.append(
                    "Column is used in a filter condition"
                )

                rows_removed = (
                    filter_info.get(
                        "rows_removed"
                    ) or 0
                )

                # -----------------------------------------
                # Rows removed by filter
                # -----------------------------------------

                if rows_removed > 10000:

                    score += 25

                    reasons.append(
                        "Very high rows removed by filter"
                    )

                elif rows_removed > 1000:

                    score += 15

                    reasons.append(
                        "High rows removed by filter"
                    )

                elif rows_removed > 100:

                    score += 10

                    reasons.append(
                        "Significant rows removed by filter"
                    )

                elif rows_removed > 0:

                    score += 5

                    reasons.append(
                        "Rows removed by filter"
                    )

        # -------------------------------------------------
        # 2. Sequential scan evidence
        # -------------------------------------------------

        sequential_scan_detected = False

        for scan in features.get(
            "scan_nodes",
            []
        ):

            scan_table = scan.get(
                "table"
            )

            scan_type = scan.get(
                "node_type"
            )

            if (
                scan_table == table
                and scan_type == "Seq Scan"
            ):

                sequential_scan_detected = True
                break

        if sequential_scan_detected:

            score += 20

            reasons.append(
                "Sequential scan detected on candidate table"
            )

        # -------------------------------------------------
        # 3. Join evidence
        # -------------------------------------------------

        if reason == "Join condition":

            score += 15

            reasons.append(
                "Column participates in a join"
            )

        # -------------------------------------------------
        # 4. ORDER BY evidence
        # -------------------------------------------------

        if reason == "ORDER BY":

            score += 10

            reasons.append(
                "Column is used for sorting"
            )

        # -------------------------------------------------
        # 5. GROUP BY evidence
        # -------------------------------------------------

        if reason == "GROUP BY":

            score += 10

            reasons.append(
                "Column is used for grouping"
            )

        # -------------------------------------------------
        # 6. Existing index check
        # -------------------------------------------------

        if features.get(
            "has_index_condition"
        ):

            # This does not automatically eliminate
            # the candidate, but reduces its priority.

            score -= 20

            reasons.append(
                "An index condition already exists in the plan"
            )

        # -------------------------------------------------
        # 7. Cap score
        # -------------------------------------------------

        score = max(
            0,
            min(
                score,
                100
            )
        )

        # -------------------------------------------------
        # Build result
        # -------------------------------------------------

        scored_candidate = candidate.copy()

        scored_candidate[
            "score"
        ] = score

        scored_candidate[
            "reasons"
        ] = reasons

        scored_candidates.append(
            scored_candidate
        )

    # -----------------------------------------------------
    # Sort by score
    # -----------------------------------------------------

    scored_candidates.sort(
        key=lambda candidate:
            candidate["score"],
        reverse=True
    )

    # -----------------------------------------------------
    # Assign priority
    # -----------------------------------------------------

    for candidate in scored_candidates:

        score = candidate["score"]

        if score >= 70:

            priority = "High"

        elif score >= 40:

            priority = "Medium"

        else:

            priority = "Low"

        candidate[
            "priority"
        ] = priority

    return scored_candidates


# =========================================================
# DISPLAY RESULTS
# =========================================================

def print_recommendations(
    recommendations
):
    """
    Print scored candidates and their evidence.
    """

    print("\n" + "=" * 70)
    print("INDEX RECOMMENDATIONS")
    print("=" * 70)

    if not recommendations:

        print(
            "No index recommendations generated."
        )

        print("=" * 70)

        return

    for number, recommendation in enumerate(
        recommendations,
        start=1
    ):

        table = recommendation[
            "table_name"
        ]

        columns = recommendation[
            "column_name"
        ]

        score = recommendation[
            "score"
        ]

        priority = recommendation[
            "priority"
        ]

        print(
            f"\nRecommendation {number}"
        )

        print(
            f"  Table       : {table}"
        )

        print(
            f"  Columns     : {columns}"
        )

        print(
            f"  Index type  : "
            f"{recommendation['index_type']}"
        )

        print(
            f"  Score       : {score}/100"
        )

        print(
            f"  Priority    : {priority}"
        )

        print(
            f"  Reason      : "
            f"{recommendation['reason']}"
        )

        print(
            "  Evidence:"
        )

        for reason in recommendation[
            "reasons"
        ]:

            print(
                f"    - {reason}"
            )

        print(
            f"  Source      : "
            f"{recommendation['source']}"
        )

    print("\n" + "=" * 70)
