"""
Recommendation Quality Analyzer
--------------------------------
Builds a reproducible analytical dataset combining:

    Query Profiles
        +
    Index Recommendations
        +
    Workload Metrics
        +
    Benchmark / Validation Outcomes

This module is analytical only.

It does NOT:
    - modify recommendations
    - create indexes
    - modify benchmark results
    - change validation decisions

M14.1 purpose:
    Create the Recommendation–Workload–Validation
    analytical dataset used for subsequent experimental
    evaluation and recommendation-quality analysis.
"""

from config.database import get_connection
from collector.query_parser import QueryFingerprinter


# =========================================================
# LOAD RECOMMENDATIONS + QUERY PROFILES + BENCHMARKS
# =========================================================

def load_recommendation_evaluation_records():
    """
    Load recommendation records joined with their query
    profile and benchmark / validation evidence.

    One returned record represents one recommendation /
    benchmark observation.

    Recommendations without benchmark evidence are retained
    through the LEFT JOIN, with benchmark fields set to None.

    Multiple benchmark experiments for the same recommendation
    are intentionally preserved as separate analytical rows.
    """

    conn = get_connection()

    try:
        cur = conn.cursor()

        cur.execute(
            """
            SELECT
                r.recommendation_id,
                r.query_profile_id,
                r.table_name,
                r.column_name,
                r.index_type,
                r.recommendation_score,
                r.priority,
                r.reasoning,

                qp.query_hash,
                qp.query_text,
                qp.query_type,
                qp.execution_count,
                qp.total_execution_time_ms,
                qp.average_execution_time_ms,
                qp.rows_processed,

                b.benchmark_id,
                b.execution_time_before_ms,
                b.execution_time_after_ms,
                b.improvement_percentage,
                b.median_before_ms,
                b.median_after_ms,
                b.median_improvement_percentage,
                b.rows_before,
                b.rows_after,
                b.rows_preserved,
                b.index_used,
                b.index_node_type,
                b.plan_changed,
                b.validation_status,
                b.validation_reason

            FROM index_recommendations r

            JOIN query_profiles qp
                ON r.query_profile_id = qp.query_profile_id

            LEFT JOIN benchmark_results b
                ON r.recommendation_id = b.recommendation_id

            ORDER BY
                r.recommendation_id,
                b.benchmark_id;
            """
        )

        columns = [
            description[0]
            for description in cur.description
        ]

        rows = cur.fetchall()

        return [
            dict(zip(columns, row))
            for row in rows
        ]

    finally:
        cur.close()
        conn.close()


# =========================================================
# WORKLOAD METRIC LOOKUP
# =========================================================

def build_workload_lookup(workload_analysis):
    """
    Build a fingerprint -> workload metrics lookup.

    The workload analysis is expected to contain groups
    generated by the existing workload-cost analysis layer.

    Example group:

        {
            "fingerprint": "...",
            "workload_cost_rank": 1,
            "execution_time_share": 90.45,
            "execution_frequency_share": 16.67,
            "total_executions": 3,
            "total_execution_time_ms": 1492.131,
            "total_rows_processed": 15914
        }
    """

    lookup = {}

    for group in workload_analysis.get("groups", []):

        fingerprint = group.get("fingerprint")

        if not fingerprint:
            continue

        lookup[fingerprint] = {
            "workload_cost_rank": group.get(
                "workload_cost_rank"
            ),
            "execution_time_share": group.get(
                "execution_time_share"
            ),
            "execution_frequency_share": group.get(
                "execution_frequency_share"
            ),
            "total_executions": group.get(
                "total_executions"
            ),
            "total_execution_time_ms": group.get(
                "total_execution_time_ms"
            ),
            "total_rows_processed": group.get(
                "total_rows_processed"
            ),
        }

    return lookup


# =========================================================
# WORKLOAD PRIORITY
# =========================================================

def calculate_workload_priority(
    execution_time_share,
    execution_frequency_share
):
    """
    Assign workload priority using the existing M13
    workload-priority rules.

    Rules:

        >= 50% execution-time share -> Critical
        >= 10% execution-time share -> High
        >= 5% execution-time share
            OR >= 10% execution-frequency share -> Moderate
        otherwise -> Low

    If workload metrics are unavailable, return Unknown.
    """

    if execution_time_share is None:
        return "Unknown"

    if execution_time_share >= 50:
        return "Critical"

    if execution_time_share >= 10:
        return "High"

    if (
        execution_time_share >= 5
        or (
            execution_frequency_share is not None
            and execution_frequency_share >= 10
        )
    ):
        return "Moderate"

    return "Low"


# =========================================================
# EVALUATION IMPROVEMENT
# =========================================================

def get_evaluation_improvement(record):
    """
    Return the improvement metric used for M14 evaluation.

    Preferred metric:
        median_improvement_percentage

    Fallback:
        improvement_percentage

    The fallback is necessary because the current stored
    benchmark records contain NULL median fields.

    No median value is fabricated.
    """

    median_improvement = record.get(
        "median_improvement_percentage"
    )

    if median_improvement is not None:
        return median_improvement

    return record.get(
        "improvement_percentage"
    )


# =========================================================
# BUILD ANALYTICAL DATASET
# =========================================================

def build_recommendation_evaluation_dataset(
    workload_analysis,
    records=None
):
    """
    Build the M14.1 Recommendation–Workload–Validation
    analytical dataset.

    Each row contains:

        1. Recommendation information
        2. Query profile information
        3. Query fingerprint information
        4. Workload information
        5. Benchmark information
        6. Validation information

    Multiple benchmark observations for the same
    recommendation remain separate rows.
    """

    if records is None:
        records = (
            load_recommendation_evaluation_records()
        )

    workload_lookup = build_workload_lookup(
        workload_analysis
    )

    fingerprinter = QueryFingerprinter()

    dataset = []

    for record in records:

        query_text = record.get(
            "query_text"
        ) or ""

        # -------------------------------------------------
        # Generate fingerprint correctly.
        #
        # QueryFingerprinter.generate_fingerprint()
        # returns:
        #
        #     fingerprint, normalized_template
        # -------------------------------------------------

        fingerprint = None
        normalized_template = None

        if query_text:

            (
                fingerprint,
                normalized_template
            ) = fingerprinter.generate_fingerprint(
                query_text
            )

        # -------------------------------------------------
        # Match query fingerprint against workload analysis
        # -------------------------------------------------

        workload = workload_lookup.get(
            fingerprint,
            {}
        )

        workload_match = bool(workload)

        execution_time_share = workload.get(
            "execution_time_share"
        )

        execution_frequency_share = workload.get(
            "execution_frequency_share"
        )

        # -------------------------------------------------
        # Determine evaluation improvement metric
        # -------------------------------------------------

        evaluation_improvement = (
            get_evaluation_improvement(
                record
            )
        )

        # -------------------------------------------------
        # Build analytical record
        # -------------------------------------------------

        analytical_record = {

            # =============================================
            # RECOMMENDATION
            # =============================================

            "recommendation_id": record.get(
                "recommendation_id"
            ),

            "query_profile_id": record.get(
                "query_profile_id"
            ),

            "table_name": record.get(
                "table_name"
            ),

            "column_name": record.get(
                "column_name"
            ),

            "index_type": record.get(
                "index_type"
            ),

            "recommendation_score": record.get(
                "recommendation_score"
            ),

            "recommendation_priority": record.get(
                "priority"
            ),

            "reasoning": record.get(
                "reasoning"
            ),

            # =============================================
            # QUERY
            # =============================================

            "query_hash": record.get(
                "query_hash"
            ),

            "query_text": query_text,

            "query_type": record.get(
                "query_type"
            ),

            "fingerprint": fingerprint,

            "normalized_template": (
                normalized_template
            ),

            # =============================================
            # PROFILED QUERY INFORMATION
            # =============================================

            "profile_execution_count": record.get(
                "execution_count"
            ),

            "profile_total_execution_time_ms": (
                record.get(
                    "total_execution_time_ms"
                )
            ),

            "profile_average_execution_time_ms": (
                record.get(
                    "average_execution_time_ms"
                )
            ),

            "profile_rows_processed": record.get(
                "rows_processed"
            ),

            # =============================================
            # WORKLOAD METRICS
            # =============================================

            "workload_match": workload_match,

            "workload_cost_rank": workload.get(
                "workload_cost_rank"
            ),

            "execution_time_share": (
                execution_time_share
            ),

            "execution_frequency_share": (
                execution_frequency_share
            ),

            "workload_total_executions": (
                workload.get(
                    "total_executions"
                )
            ),

            "workload_total_execution_time_ms": (
                workload.get(
                    "total_execution_time_ms"
                )
            ),

            "workload_total_rows_processed": (
                workload.get(
                    "total_rows_processed"
                )
            ),

            "workload_priority": (
                calculate_workload_priority(
                    execution_time_share,
                    execution_frequency_share
                )
            ),

            # =============================================
            # BENCHMARK
            # =============================================

            "benchmark_id": record.get(
                "benchmark_id"
            ),

            "execution_time_before_ms": (
                record.get(
                    "execution_time_before_ms"
                )
            ),

            "execution_time_after_ms": (
                record.get(
                    "execution_time_after_ms"
                )
            ),

            "improvement_percentage": (
                record.get(
                    "improvement_percentage"
                )
            ),

            "median_before_ms": (
                record.get(
                    "median_before_ms"
                )
            ),

            "median_after_ms": (
                record.get(
                    "median_after_ms"
                )
            ),

            "median_improvement_percentage": (
                record.get(
                    "median_improvement_percentage"
                )
            ),

            # Explicit M14 evaluation metric.
            #
            # Median is preferred when present.
            # Existing records currently contain NULL
            # median values, so average improvement is used
            # as the documented fallback.

            "evaluation_improvement_percentage": (
                evaluation_improvement
            ),

            # =============================================
            # VALIDATION
            # =============================================

            "rows_before": record.get(
                "rows_before"
            ),

            "rows_after": record.get(
                "rows_after"
            ),

            "rows_preserved": record.get(
                "rows_preserved"
            ),

            "index_used": record.get(
                "index_used"
            ),

            "index_node_type": record.get(
                "index_node_type"
            ),

            "plan_changed": record.get(
                "plan_changed"
            ),

            "validation_status": record.get(
                "validation_status"
            ),

            "validation_reason": record.get(
                "validation_reason"
            ),
        }

        dataset.append(
            analytical_record
        )

    return dataset


# =========================================================
# SUMMARY
# =========================================================

def summarize_evaluation_dataset(dataset):
    """
    Return structural statistics for the M14.1
    analytical dataset.
    """

    recommendation_ids = {
        row["recommendation_id"]
        for row in dataset
        if row.get("recommendation_id") is not None
    }

    benchmark_ids = {
        row["benchmark_id"]
        for row in dataset
        if row.get("benchmark_id") is not None
    }

    fingerprints = {
        row["fingerprint"]
        for row in dataset
        if row.get("fingerprint")
    }

    validated_rows = sum(
        1
        for row in dataset
        if row.get("benchmark_id") is not None
    )

    workload_matched_rows = sum(
        1
        for row in dataset
        if row.get("workload_match")
    )

    rows_without_benchmark = sum(
        1
        for row in dataset
        if row.get("benchmark_id") is None
    )

    rows_with_evaluation_improvement = sum(
        1
        for row in dataset
        if row.get(
            "evaluation_improvement_percentage"
        ) is not None
    )

    return {
        "dataset_rows": len(dataset),

        "unique_recommendations": len(
            recommendation_ids
        ),

        "unique_benchmarks": len(
            benchmark_ids
        ),

        "unique_fingerprints": len(
            fingerprints
        ),

        "validated_rows": validated_rows,

        "workload_matched_rows": (
            workload_matched_rows
        ),

        "rows_without_benchmark": (
            rows_without_benchmark
        ),

        "rows_with_evaluation_improvement": (
            rows_with_evaluation_improvement
        ),
    }


# =========================================================
# DISPLAY
# =========================================================

def print_evaluation_dataset_summary(
    dataset,
    summary=None
):
    """
    Print a concise M14.1 dataset summary and sample
    analytical records.
    """

    if summary is None:
        summary = summarize_evaluation_dataset(
            dataset
        )

    print("\n" + "=" * 90)
    print(
        "M14.1 RECOMMENDATION–WORKLOAD–VALIDATION DATASET"
    )
    print("=" * 90)

    print(
        f"Dataset rows               : "
        f"{summary['dataset_rows']}"
    )

    print(
        f"Unique recommendations     : "
        f"{summary['unique_recommendations']}"
    )

    print(
        f"Unique benchmarks          : "
        f"{summary['unique_benchmarks']}"
    )

    print(
        f"Unique fingerprints        : "
        f"{summary['unique_fingerprints']}"
    )

    print(
        f"Validated rows             : "
        f"{summary['validated_rows']}"
    )

    print(
        f"Workload-matched rows      : "
        f"{summary['workload_matched_rows']}"
    )

    print(
        f"Rows without benchmark     : "
        f"{summary['rows_without_benchmark']}"
    )

    print(
        f"Rows with evaluation metric: "
        f"{summary['rows_with_evaluation_improvement']}"
    )

    print("=" * 90)

    if not dataset:
        print("\nNo analytical records found.")
        return

    print("\nSample analytical records:")

    for row in dataset[:5]:

        print(
            f"\nRecommendation "
            f"{row['recommendation_id']}"
        )

        print(
            f"  Query Profile          : "
            f"{row['query_profile_id']}"
        )

        print(
            f"  Candidate              : "
            f"{row['table_name']}."
            f"{row['column_name']}"
        )

        print(
            f"  Recommendation Score   : "
            f"{row['recommendation_score']}"
        )

        print(
            f"  Recommendation Level   : "
            f"{row['recommendation_priority']}"
        )

        print(
            f"  Fingerprint            : "
            f"{row['fingerprint']}"
        )

        print(
            f"  Workload Match         : "
            f"{row['workload_match']}"
        )

        print(
            f"  Workload Rank          : "
            f"{row['workload_cost_rank']}"
        )

        print(
            f"  Workload Priority      : "
            f"{row['workload_priority']}"
        )

        print(
            f"  Execution Time Share   : "
            f"{row['execution_time_share']}"
        )

        print(
            f"  Execution Frequency    : "
            f"{row['execution_frequency_share']}"
        )

        print(
            f"  Benchmark ID           : "
            f"{row['benchmark_id']}"
        )

        print(
            f"  Average Improvement    : "
            f"{row['improvement_percentage']}"
        )

        print(
            f"  Median Improvement     : "
            f"{row['median_improvement_percentage']}"
        )

        print(
            f"  Evaluation Improvement : "
            f"{row['evaluation_improvement_percentage']}"
        )

        print(
            f"  Rows Preserved         : "
            f"{row['rows_preserved']}"
        )

        print(
            f"  Index Used             : "
            f"{row['index_used']}"
        )

        print(
            f"  Plan Changed           : "
            f"{row['plan_changed']}"
        )

        print(
            f"  Validation Status      : "
            f"{row['validation_status']}"
        )


# =========================================================
# MAIN
# =========================================================

if __name__ == "__main__":

    from collector.workload_cost_analyzer import (
        analyze_workload_costs
    )

    # -----------------------------------------------------
    # Generate the existing workload analysis.
    # -----------------------------------------------------

    workload_analysis = (
        analyze_workload_costs()
    )

    # -----------------------------------------------------
    # Build M14.1 analytical dataset.
    # -----------------------------------------------------

    dataset = (
        build_recommendation_evaluation_dataset(
            workload_analysis
        )
    )

    # -----------------------------------------------------
    # Calculate structural summary.
    # -----------------------------------------------------

    summary = summarize_evaluation_dataset(
        dataset
    )

    # -----------------------------------------------------
    # Display result.
    # -----------------------------------------------------

    print_evaluation_dataset_summary(
        dataset,
        summary
    )
