"""
Recommendation Repository
-------------------------
Persists index recommendations generated by
the recommendation engine into PostgreSQL.
"""

from datetime import datetime

from config.database import get_connection


# =========================================================
# GENERATE INDEX SQL
# =========================================================

def generate_index_sql(
    table_name,
    column_name,
    index_type="B-tree"
):
    """
    Generate PostgreSQL CREATE INDEX statement.
    """

    index_name = f"idx_{table_name}_{column_name}"

    normalized_type = (
        index_type
        .strip()
        .lower()
        .replace("-", "")
    )

    if normalized_type == "btree":

        return (
            f"CREATE INDEX {index_name} "
            f"ON {table_name} USING BTREE "
            f"({column_name});"
        )

    raise ValueError(
        f"Unsupported index type: {index_type}"
    )


# =========================================================
# SAVE ONE RECOMMENDATION
# =========================================================

def save_recommendation(
    query_profile_id,
    table_name,
    column_name,
    index_type,
    recommendation_score,
    priority,
    reasoning
):
    """
    Save one recommendation.

    If the same query profile, table, column,
    and index type already exist, return the
    existing recommendation ID instead of
    creating a duplicate.
    """

    index_sql = generate_index_sql(
        table_name,
        column_name,
        index_type
    )

    conn = get_connection()

    try:

        cur = conn.cursor()

        # -------------------------------------------------
        # Check for existing recommendation
        # -------------------------------------------------

        cur.execute(
            """
            SELECT recommendation_id
            FROM index_recommendations
            WHERE query_profile_id = %s
              AND table_name = %s
              AND column_name = %s
              AND index_type = %s
            ORDER BY recommendation_id
            LIMIT 1;
            """,
            (
                query_profile_id,
                table_name,
                column_name,
                index_type
            )
        )

        existing = cur.fetchone()

        if existing:

            recommendation_id = existing[0]

            conn.commit()

            return recommendation_id

        # -------------------------------------------------
        # Insert new recommendation
        # -------------------------------------------------

        cur.execute(
            """
            INSERT INTO index_recommendations (
                query_profile_id,
                table_name,
                column_name,
                index_type,
                recommendation_score,
                priority,
                reasoning,
                index_sql,
                created_at
            )
            VALUES (
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s
            )
            RETURNING recommendation_id;
            """,
            (
                query_profile_id,
                table_name,
                column_name,
                index_type,
                recommendation_score,
                priority,
                reasoning,
                index_sql,
                datetime.now()
            )
        )

        recommendation_id = cur.fetchone()[0]

        conn.commit()

        return recommendation_id

    except Exception:

        conn.rollback()

        raise

    finally:

        cur.close()
        conn.close()


# =========================================================
# SAVE MULTIPLE RECOMMENDATIONS
# =========================================================

def save_recommendations(
    query_profile_id,
    recommendations
):
    """
    Save all recommendations generated for
    a query profile.

    Duplicate recommendations are not created.
    """

    recommendation_ids = []

    for recommendation in recommendations:

        table_name = recommendation[
            "table_name"
        ]

        column_name = recommendation[
            "column_name"
        ]

        index_type = recommendation.get(
            "index_type",
            "B-tree"
        )

        score = recommendation.get(
            "score",
            0
        )

        priority = recommendation.get(
            "priority",
            "Low"
        )

        evidence = recommendation.get(
            "reasons",
            []
        )

        reason = recommendation.get(
            "reason",
            ""
        )

        # -------------------------------------------------
        # Combine reason + evidence
        # -------------------------------------------------

        reasoning_parts = []

        if reason:
            reasoning_parts.append(
                reason
            )

        reasoning_parts.extend(
            evidence
        )

        reasoning = "; ".join(
            reasoning_parts
        )

        # -------------------------------------------------
        # Save
        # -------------------------------------------------

        recommendation_id = save_recommendation(
            query_profile_id=query_profile_id,
            table_name=table_name,
            column_name=column_name,
            index_type=index_type,
            recommendation_score=score,
            priority=priority,
            reasoning=reasoning
        )

        recommendation_ids.append(
            recommendation_id
        )

    return recommendation_ids


# =========================================================
# DISPLAY SAVED RECOMMENDATIONS
# =========================================================

def print_saved_recommendations(
    recommendation_ids
):
    """
    Display recommendations that were saved
    or reused.
    """

    print("\n" + "=" * 70)
    print("SAVED RECOMMENDATIONS")
    print("=" * 70)

    if not recommendation_ids:

        print(
            "No recommendations were saved."
        )

        print("=" * 70)

        return

    conn = get_connection()

    try:

        cur = conn.cursor()

        cur.execute(
            """
            SELECT
                recommendation_id,
                query_profile_id,
                table_name,
                column_name,
                index_type,
                recommendation_score,
                priority,
                index_sql
            FROM index_recommendations
            WHERE recommendation_id = ANY(%s)
            ORDER BY recommendation_id;
            """,
            (recommendation_ids,)
        )

        for row in cur.fetchall():

            print(
                f"\nRecommendation ID : {row[0]}"
            )

            print(
                f"Query Profile ID  : {row[1]}"
            )

            print(
                f"Table             : {row[2]}"
            )

            print(
                f"Column            : {row[3]}"
            )

            print(
                f"Index Type        : {row[4]}"
            )

            print(
                f"Score             : {row[5]}/100"
            )

            print(
                f"Priority          : {row[6]}"
            )

            print(
                f"Index SQL         : {row[7]}"
            )

    finally:

        cur.close()
        conn.close()

    print("\n" + "=" * 70)
