"""
Recommendation Repository
-------------------------
Persists index recommendations generated by
the recommendation engine into PostgreSQL.
"""

from datetime import datetime
import re

from config.database import get_connection


# =========================================================
# INDEX NAME HELPERS
# =========================================================

def normalize_index_name_part(value):
    """
    Convert a table or column expression into a safe
    PostgreSQL index-name component.

    Composite column expressions such as:

        customer_id, status

    become:

        customer_id_status
    """

    value = str(value).strip()

    # Replace separators and whitespace with underscores.
    value = re.sub(
        r"[^a-zA-Z0-9_]+",
        "_",
        value
    )

    # Collapse repeated underscores.
    value = re.sub(
        r"_+",
        "_",
        value
    )

    # Remove leading/trailing underscores.
    value = value.strip("_")

    return value


def generate_index_name(
    table_name,
    column_name
):
    """
    Generate a valid PostgreSQL index name.

    Examples
    --------
    orders + customer_id
        -> idx_orders_customer_id

    orders + customer_id, status
        -> idx_orders_customer_id_status
    """

    table_part = normalize_index_name_part(
        table_name
    )

    column_part = normalize_index_name_part(
        column_name
    )

    index_name = (
        f"idx_{table_part}_{column_part}"
    )

    # PostgreSQL identifiers are limited to 63 bytes.
    # The generated names here are ASCII, so character
    # length is sufficient for this project.
    return index_name[:63]


# =========================================================
# GENERATE INDEX SQL
# =========================================================

def generate_index_sql(
    table_name,
    column_name,
    index_type="B-tree"
):
    """
    Generate PostgreSQL CREATE INDEX statement.

    Supports both single-column and composite
    index candidates.

    Examples
    --------
    Single column:

        CREATE INDEX idx_orders_customer_id
        ON orders USING BTREE (customer_id);

    Composite:

        CREATE INDEX idx_orders_customer_id_status
        ON orders USING BTREE (customer_id, status);
    """

    index_name = generate_index_name(
        table_name,
        column_name
    )

    normalized_type = (
        index_type
        .strip()
        .lower()
        .replace("-", "")
        .replace(" ", "")
    )

    if normalized_type == "btree":

        return (
            f"CREATE INDEX {index_name} "
            f"ON {table_name} USING BTREE "
            f"({column_name});"
        )

    raise ValueError(
        f"Unsupported index type: {index_type}"
    )


# =========================================================
# SAVE ONE RECOMMENDATION
# =========================================================

def save_recommendation(
    query_profile_id,
    table_name,
    column_name,
    index_type,
    recommendation_score,
    priority,
    reasoning
):
    """
    Save one recommendation.

    If the same query profile, table, column,
    and index type already exist, return the
    existing recommendation ID instead of
    creating a duplicate.
    """

    index_sql = generate_index_sql(
        table_name,
        column_name,
        index_type
    )

    conn = get_connection()

    try:

        cur = conn.cursor()

        # -------------------------------------------------
        # Check for existing recommendation
        # -------------------------------------------------

        cur.execute(
            """
            SELECT recommendation_id
            FROM index_recommendations
            WHERE query_profile_id = %s
              AND table_name = %s
              AND column_name = %s
              AND index_type = %s
            ORDER BY recommendation_id
            LIMIT 1;
            """,
            (
                query_profile_id,
                table_name,
                column_name,
                index_type
            )
        )

        existing = cur.fetchone()

        if existing:

            recommendation_id = existing[0]

            conn.commit()

            return recommendation_id

        # -------------------------------------------------
        # Insert new recommendation
        # -------------------------------------------------

        cur.execute(
            """
            INSERT INTO index_recommendations (
                query_profile_id,
                table_name,
                column_name,
                index_type,
                recommendation_score,
                priority,
                reasoning,
                index_sql,
                created_at
            )
            VALUES (
                %s, %s, %s, %s, %s,
                %s, %s, %s, %s
            )
            RETURNING recommendation_id;
            """,
            (
                query_profile_id,
                table_name,
                column_name,
                index_type,
                recommendation_score,
                priority,
                reasoning,
                index_sql,
                datetime.now()
            )
        )

        recommendation_id = cur.fetchone()[0]

        conn.commit()

        return recommendation_id

    except Exception:

        conn.rollback()

        raise

    finally:

        cur.close()
        conn.close()


# =========================================================
# SAVE MULTIPLE RECOMMENDATIONS
# =========================================================

def save_recommendations(
    query_profile_id,
    recommendations
):
    """
    Save all recommendations generated for
    a query profile.

    Duplicate recommendations are not created.
    """

    recommendation_ids = []

    for recommendation in recommendations:

        table_name = recommendation[
            "table_name"
        ]

        column_name = recommendation[
            "column_name"
        ]

        index_type = recommendation.get(
            "index_type",
            "B-tree"
        )

        score = recommendation.get(
            "score",
            0
        )

        priority = recommendation.get(
            "priority",
            "Low"
        )

        evidence = recommendation.get(
            "reasons",
            []
        )

        reason = recommendation.get(
            "reason",
            ""
        )

        # -------------------------------------------------
        # Combine reason + evidence
        # -------------------------------------------------

        reasoning_parts = []

        if reason:
            reasoning_parts.append(
                reason
            )

        reasoning_parts.extend(
            evidence
        )

        reasoning = "; ".join(
            reasoning_parts
        )

        # -------------------------------------------------
        # Save
        # -------------------------------------------------

        recommendation_id = save_recommendation(
            query_profile_id=query_profile_id,
            table_name=table_name,
            column_name=column_name,
            index_type=index_type,
            recommendation_score=score,
            priority=priority,
            reasoning=reasoning
        )

        recommendation_ids.append(
            recommendation_id
        )

    return recommendation_ids


# =========================================================
# DISPLAY SAVED RECOMMENDATIONS
# =========================================================

def print_saved_recommendations(
    recommendation_ids
):
    """
    Print saved recommendation records.
    """

    if not recommendation_ids:

        print(
            "\nNo recommendation records "
            "were saved."
        )

        return

    conn = get_connection()

    try:

        cur = conn.cursor()

        cur.execute(
            """
            SELECT
                recommendation_id,
                query_profile_id,
                table_name,
                column_name,
                index_type,
                recommendation_score,
                priority,
                reasoning,
                index_sql,
                created_at
            FROM index_recommendations
            WHERE recommendation_id = ANY(%s)
            ORDER BY recommendation_id;
            """,
            (
                recommendation_ids,
            )
        )

        rows = cur.fetchall()

    finally:

        cur.close()
        conn.close()

    print(
        "\n" + "=" * 80
    )

    print(
        "SAVED RECOMMENDATIONS"
    )

    print(
        "=" * 80
    )

    for row in rows:

        (
            recommendation_id,
            query_profile_id,
            table_name,
            column_name,
            index_type,
            recommendation_score,
            priority,
            reasoning,
            index_sql,
            created_at
        ) = row

        print(
            f"\nRecommendation ID : "
            f"{recommendation_id}"
        )

        print(
            f"Query Profile ID  : "
            f"{query_profile_id}"
        )

        print(
            f"Index Candidate    : "
            f"{table_name}.{column_name}"
        )

        print(
            f"Index Type        : "
            f"{index_type}"
        )

        print(
            f"Score             : "
            f"{recommendation_score}"
        )

        print(
            f"Priority          : "
            f"{priority}"
        )

        print(
            f"Reasoning         : "
            f"{reasoning}"
        )

        print(
            f"Index SQL         : "
            f"{index_sql}"
        )

        print(
            f"Created At        : "
            f"{created_at}"
        )

    print(
        "\n" + "=" * 80
    )
